In [1]:
import pandas as pd
import time

In [4]:
start = time.time()

print("FILE LOADED! This took", time.time() - start, " seconds")
df = pd.read_csv(
    "../data/itineraries.csv",
    chunksize=100000
)

FILE LOADED! This took 0.0  seconds

In [5]:
temp_df = None
for chunk in df:
    temp_df = chunk
    break

In [6]:

with pd.option_context('display.max_columns', None):
    display(temp_df)

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,isNonStop,baseFare,totalFare,seatsRemaining,totalTravelDistance,segmentsDepartureTimeEpochSeconds,segmentsDepartureTimeRaw,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,9ca0e81111c683bec1012473feefd28f,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H29M,0,False,False,True,217.67,248.60,9,947.0,1650214620,2022-04-17T12:57:00.000-04:00,1650223560,2022-04-17T15:26:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,8940,947,coach
1,98685953630e772a098941b71906592b,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,True,217.67,248.60,4,947.0,1650191400,2022-04-17T06:30:00.000-04:00,1650200400,2022-04-17T09:00:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9000,947,coach
2,98d90cbc32bfbb05c2fc32897c7c1087,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,True,217.67,248.60,9,947.0,1650209700,2022-04-17T11:35:00.000-04:00,1650218700,2022-04-17T14:05:00.000-04:00,BOS,ATL,Delta,DL,Boeing 757-200,9000,947,coach
3,969a269d38eae583f455486fa90877b4,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H32M,0,False,False,True,217.67,248.60,8,947.0,1650218340,2022-04-17T13:59:00.000-04:00,1650227460,2022-04-17T16:31:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9120,947,coach
4,980370cf27c89b40d2833a1d5afc9751,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H34M,0,False,False,True,217.67,248.60,9,947.0,1650203940,2022-04-17T09:59:00.000-04:00,1650213180,2022-04-17T12:33:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9240,947,coach
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,02a4d527796ca5bd8be5b0e8e3d85acd,2022-04-17,2022-04-19,EWR,DEN,LAA3JHEN,PT8H36M,0,False,False,False,115.35,147.60,4,2295.0,1650361440||1650383700,2022-04-19T05:44:00.000-04:00||2022-04-19T10:5...,1650374940||1650392400,2022-04-19T08:29:00.000-05:00||2022-04-19T12:2...,IAH||DEN,EWR||IAH,United||United,UA||UA,Boeing 737-900||BOEING 787-9,13500||8700,1419||876,coach||coach
99996,416ff0256a24791b8924f91c354901ac,2022-04-17,2022-04-19,EWR,DEN,LAA3JHEN,PT8H58M,0,False,False,False,115.35,147.60,4,1623.0,1650395820||1650418200,2022-04-19T15:17:00.000-04:00||2022-04-19T20:3...,1650405180||1650428100,2022-04-19T16:53:00.000-05:00||2022-04-19T22:1...,ORD||DEN,EWR||ORD,United||United,UA||UA,Boeing 737-800||Boeing 757-200,9360||9900,720||903,coach||coach
99997,e7806daf62b3d0eb0f801337bacdc496,2022-04-17,2022-04-19,EWR,DEN,N3AJZSN3,PT8H59M,0,False,False,False,115.35,147.60,3,2030.0,1650364440||1650389280,2022-04-19T06:34:00.000-04:00||2022-04-19T12:2...,1650378840||1650396780,2022-04-19T09:34:00.000-05:00||2022-04-19T13:3...,DFW||DEN,EWR||DFW,American Airlines||American Airlines,AA||AA,Airbus A321||Airbus A321,14400||7500,1380||650,coach||coach
99998,baac14d391f0026f78698e0915f92818,2022-04-17,2022-04-19,EWR,DEN,VA3NA0BC,PT9H3M,0,True,False,False,115.35,147.60,9,1702.0,1650395460||1650420300,2022-04-19T15:11:00.000-04:00||2022-04-19T21:0...,1650406320||1650428040,2022-04-19T17:12:00.000-05:00||2022-04-19T22:1...,MSP||DEN,EWR||MSP,Delta||Delta,DL||DL,Canadair Regional Jet 900||Boeing 737-900,10860||7740,1009||693,coach||coach
99999,61464bc6b979fa0cfba42d370a1da2a5,2022-04-17,2022-04-19,EWR,DEN,TAA3JHEN,PT4H14M,0,False,False,True,143.26,168.61,1,1621.0,1650385740,2022-04-19T12:29:00.000-04:00,1650400980,2022-04-19T14:43:00.000-06:00,DEN,EWR,United,UA,Boeing 737-900,15240,1621,coach

In [37]:
count = 0
temp_df = None
for chunk in df:
    print(chunk.shape)
    count += 1
    print(count)

(1000000, 27)
1
(1000000, 27)
2
(1000000, 27)
3
(1000000, 27)
4
(1000000, 27)
5
(1000000, 27)
6
(1000000, 27)
7
(1000000, 27)
8
(1000000, 27)
9
(1000000, 27)
10
(1000000, 27)
11
(1000000, 27)
12
(1000000, 27)
13
(1000000, 27)
14
(1000000, 27)
15
(1000000, 27)
16
(1000000, 27)
17
(1000000, 27)
18
(1000000, 27)
19
(1000000, 27)
20
(1000000, 27)
21
(1000000, 27)
22
(1000000, 27)
23
(1000000, 27)
24
(1000000, 27)
25
(1000000, 27)
26
(1000000, 27)
27
(1000000, 27)
28
(1000000, 27)
29
(1000000, 27)
30
(1000000, 27)
31
(1000000, 27)
32
(1000000, 27)
33
(1000000, 27)
34
(1000000, 27)
35
(1000000, 27)
36
(1000000, 27)
37
(1000000, 27)
38
(1000000, 27)
39
(1000000, 27)
40
(1000000, 27)
41
(1000000, 27)
42
(1000000, 27)
43
(1000000, 27)
44
(1000000, 27)
45
(1000000, 27)
46
(1000000, 27)
47
(1000000, 27)
48
(1000000, 27)
49
(1000000, 27)
50
(1000000, 27)
51
(1000000, 27)
52
(1000000, 27)
53
(1000000, 27)
54
(1000000, 27)
55
(1000000, 27)
56
(1000000, 27)
57
(1000000, 27)
58
(1000000, 27)
59
(1000000, 27)
60
(1000000, 27)
61
(1000000, 27)
62
(1000000, 27)
63
(1000000, 27)
64
(1000000, 27)
65
(1000000, 27)
66
(1000000, 27)
67
(1000000, 27)
68
(1000000, 27)
69
(1000000, 27)
70
(1000000, 27)
71
(1000000, 27)
72
(1000000, 27)
73
(1000000, 27)
74
(1000000, 27)
75
(1000000, 27)
76
(1000000, 27)
77
(1000000, 27)
78
(1000000, 27)
79
(1000000, 27)
80
(1000000, 27)
81
(138753, 27)
82